---
title: C26111
ms.date: 11/04/2016
ms.topic: reference
f1_keywords:
- C26111
helpviewer_keywords:
- C26111
ms.assetid: 85fc740a-3bbb-41b8-a848-95e243a08da9
author: corob-msft
ms.author: corob
manager: markl
ms.workload:
- multiple
ms.openlocfilehash: fb9329661f57c9b6f396c920c5cb8c78457e2bdb
ms.sourcegitcommit: 68f893f6e472df46f323db34a13a7034dccad25a
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 02/15/2020
ms.locfileid: "77270816"
---
# <a name="c26111"></a>C26111
경고 C 26111: 호출자가 함수 \<func >를 호출 하기 전에 잠금 \<> 잠금 해제에 실패 했습니다.

 `_Requires_lock_not_held_` 주석에는 함수가 호출될 때 지정된 잠금에 대한 잠금 횟수가 0보다 클 수 없다는 사전 조건이 적용됩니다. 다른 함수를 호출하기 전에 함수가 잠금을 해제하지 못할 경우 경고 C26111이 발생합니다.

## <a name="example"></a>예제
 다음 예제에서는 잠긴 섹션 내에서 `_Requires_lock_not_held_`에 대한 호출로 인해 `DoNotLock` 사전 조건이 위반되기 때문에 경고 C26111이 발생합니다.

```cpp
typedef struct _DATA
{
    CRITICAL_SECTION cs;
    int d;
} DATA;

_Requires_lock_not_held_(p->cs)

void DoNotLock(DATA* p)
{
    EnterCriticalSection(&p->cs);
    p->d = 0;
    LeaveCriticalSection(&p->cs);
}

void LockedFunction(DATA* p)
{
    EnterCriticalSection(&p->cs);
    DoNotLock(p); // Warning C26111
    LeaveCriticalSection(&p->cs);
}
```
