---
title: C6318
ms.date: 11/04/2016
ms.topic: reference
f1_keywords:
- C6318
helpviewer_keywords:
- C6318
ms.assetid: 3284a83e-bb8e-461c-adcc-cfc66ceea05e
author: mikeblome
ms.author: mblome
manager: wpickett
ms.workload:
- multiple
ms.openlocfilehash: f472860cd338dee15b4005db16ba09de1e314071
ms.sourcegitcommit: 94b3a052fb1229c7e7f8804b09c1d403385c7630
ms.translationtype: MT
ms.contentlocale: ko-KR
ms.lasthandoff: 04/23/2019
ms.locfileid: "62781897"
---
# <a name="c6318"></a>C6318
경고 C6318: 단추가 잘못 정의 __try /\__except: 상수 EXCEPTION_CONTINUE_SEARCH 또는 예외 필터 식에서 0으로 계산 되는 다른 상수를 사용 합니다. 예외 처리기 블록의 코드가 실행 되지 않습니다.

 이 경고는이 구조적된 예외 처리기의 보호 된 블록에서 예외가 발생 하는 경우 예외가 처리 되지 것입니다 있으므로 나타냅니다 상수 `EXCECPTION_CONTINUE_SEARCH` 예외 필터 식에 사용 됩니다.

 이 코드는 처리기 블록이 실행 되지 않기 때문에 예외 처리기 블록 없이 보호 된 블록에 해당 합니다.

## <a name="example"></a>예제
 다음 코드에서는이 경고를 생성합니다.

```
#include <excpt.h>
#include <stdio.h>

void f (char *pch)
{
  __try
  {
    // assignment might fail
    *pch = 0;
  }
  __except (EXCEPTION_CONTINUE_SEARCH) // warning 6318
  {
    puts("Exception Occurred");
  }
}
```

 이 경고를 해결 하려면 다음 코드를 사용 합니다.

```
#include <excpt.h>
#include <stdio.h>
#include <windows.h>

void f (char *pch)
{
  __try
  {
    // assignment might fail
    *pch = 0;
  }
  __except( (GetExceptionCode() == EXCEPTION_ACCESS_VIOLATION) ?
                EXCEPTION_EXECUTE_HANDLER : EXCEPTION_CONTINUE_SEARCH )
  {
    puts("Access violation");
  }
}
```

## <a name="see-also"></a>참고 항목
 [try-except 문](/cpp/cpp/try-except-statement)